/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/recommendations/personalized": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getPersonalized"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/personalized/grouped": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["getPersonalizedGrouped"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/wildcard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWildCard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/similar/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSimilar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recommendations/because-you-liked/{gameId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getBecauseYouLiked"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PersonalizedRequest: {
            /** Format: int32 */
            limit?: number;
            recentlyShownIds?: number[];
        };
        RecommendationDTO: {
            /** Format: int32 */
            igdbId?: number;
            name?: string;
            rating?: number;
            backgroundImage?: string;
            genres?: string[];
            platforms?: string[];
            reason?: string;
            /** Format: int32 */
            tier?: number;
        };
        GroupedRequest: {
            recentlyShownIds?: number[];
        };
        GroupedRecommendationsResponse: {
            rows?: components["schemas"]["RecommendationRow"][];
            /** Format: int32 */
            tier?: number;
            emptyMessage?: string;
        };
        RecommendationRow: {
            label?: string;
            genre?: string;
            fallback?: boolean;
            games?: components["schemas"]["RecommendationDTO"][];
        };
        BecauseYouLikedDTO: {
            /** Format: int32 */
            basedOnIgdbId?: number;
            basedOnGame?: string;
            recommendations?: components["schemas"]["RecommendationDTO"][];
        };
        DashboardDTO: {
            recommendations?: components["schemas"]["RecommendationDTO"][];
            wildcard?: components["schemas"]["RecommendationDTO"][];
            becauseYouLiked?: components["schemas"]["BecauseYouLikedDTO"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getPersonalized: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalizedRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecommendationDTO"][];
                };
            };
        };
    };
    getPersonalizedGrouped: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["GroupedRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GroupedRecommendationsResponse"];
                };
            };
        };
    };
    getWildCard: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecommendationDTO"][];
                };
            };
        };
    };
    getSimilar: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecommendationDTO"][];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DashboardDTO"];
                };
            };
        };
    };
    getBecauseYouLiked: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RecommendationDTO"][];
                };
            };
        };
    };
}
