name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: The-Game-Cellar/.github/.github/workflows/frontend.yml@main
    permissions:
      contents: read
      packages: write
